### ISSUE TITLE
dist folder in ignore file again

### ISSUE THREAD

**Issue by dgramma** [ashiguruma/patternomaly#11]
It seems the dist folder is part of the gitignore again. Is there any reason for that?

**Comment by damienfaivre** [comment]
Yeah I find it weird, I can't even execute example files… and I honestly don't know how to overpass the gitignore…

**Comment by ashiguruma** [comment]
Hi guys. Apologies for the silence. I will try and take a look into this.

**Comment by surfjones** [comment]
Any update? I too am unable to execute examples.

**Comment by ashiguruma** [comment]
Hi All. In order to run the examples locally you'll need to build the project. Once you've cloned you can run the following commands to get everything you need.

```bash
npm install
npm run build
```

This will install all required node modules and build the project. The resulting `dist` directory will contain the packaged file.

**Comment by ashiguruma** [comment]
Closing as this requires a build. Let me know if there are any issue with building.
