### ISSUE TITLE
Documentation/Examples?

### ISSUE THREAD

**Issue by obedm503** [ashiguruma/patternomaly#12]
I find this to be a really cool project. When trying to include it in my site with Chart.js I noticed that no demos of the available patterns existed, and that there is no user documentation whatsoever. So I did some source digging and found the list of patterns and put together a fiddle that might serve as demo.

https://jsfiddle.net/jLu0L0r8/

I recommend something like this is referenced in the readme.

**Comment by ashiguruma** [comment]
A very good point. In the absence of some proper documentation I've updated the [README file](https://github.com/ashiguruma/patternomaly/blob/master/README.md) with details of the available patterns.
