### ISSUE TITLE
Can't compile patternomaly properly

### ISSUE THREAD

**Issue by jnovick** [ashiguruma/patternomaly#13]
I've made no custom changes. The moment I installed and tried to use, I get the error below, but it appears to work anyway.

TypeError: undefined is not a constructor (evaluating 'Object.assign(completeS
hapesList, shapes, deprecatedShapes)')
  at webpack:///~/patternomaly/dist/patternomaly.js:1037:0 <- src/test-setup.web
pack.js:63371

PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  TypeError: undefined is not a constructor (evaluating 'Object.assign(completeS
hapesList, shapes, deprecatedShapes)')
  at webpack:///~/patternomaly/dist/patternomaly.js:1037:0 <- src/test-setup.web
pack.js:63371

**Comment by ashiguruma** [comment]
Hi @jnovick. This looks like an issue with Object.assign not being available. Please check out the branch mentioned in pull request #14 and let me know if that fixes your issue. If so I can get the changes merged and tagged.

**Comment by ashiguruma** [comment]
This should now be fixed by #24.
