### ISSUE TITLE
How to import patternomaly into typescript project?

### ISSUE THREAD

**Issue by Astacius** [ashiguruma/patternomaly#15]
Because I am using chart.js with Ionic 2 and I dont know how to do that.

**Comment by noilly** [comment]
`import * as pattern from 'patternomaly';`

**Comment by miller45** [comment]
I added a typings file for code completion and better syntax check
https://github.com/ashiguruma/patternomaly/pull/23

**Comment by blumk** [comment]
This worked for me:
`import pattern from 'patternomaly';`

**Comment by ashiguruma** [comment]
Fixed by #23. Thanks to @miller45.
