### ISSUE TITLE
Resizeable patterns

### ISSUE THREAD

**Issue by viorell91** [ashiguruma/patternomaly#18]
Hi guys,

I have a small bar chart whose bars are filled with diagonal patterns. 

![grafik](https://user-images.githubusercontent.com/12009035/37721806-c2c7e30a-2d2a-11e8-8e21-3d332cd80458.png)

Since the chart is small, the patterns look pretty ugly. Do you have any idea how to decrease the size of the pattern? I would like the diagonal lines to be more frequent and thinner.

**Comment by JoeKuhns** [comment]
when you do...
` pattern.draw('name', 'pattern color', 'background color', pattern size),`

The first variable is pattern name, the second is pattern color, the third, is background color, and the fourth is pattern size.  so put a number in the fourth spot and you are all set, I believe the default is 20.

**Comment by viorell91** [comment]
Oh, I missed the rest of the function parameters. Very nice. Thanks for quick answer.

**Comment by tommypeterz** [comment]
I haven't seen those  last two parameters mentioned anywhere else, and aren't #2 and #3 in reverse order...?

function draw() {
  var shapeType = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : 'square';
  var backgroundColor = arguments[1];
  var patternColor = arguments[2];
  var size = arguments[3];
